services:
  app:
    image: myapp
    build:
      context: .
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
    volumes:
      - ./:/app
  test:
    image: myapp
    command: npm test
    depends_on:
      - app
